USE[EmailCounts]

INSERT INTO RecipientsToCapture (EmailAddress, Department) VALUES
('Jacqueline.Bak@havenpower.com','Renewals'),
('Manoj.Nair@havenpower.com','Renewals'),
('Yiannis.Tsangaris@havenpower.com','Renewals'),
('Joanne.Moore@havenpower.com','Renewals'),
('Max.Wilding@havenpower.com','Renewals'),
('Sharon.Sharp@havenpower.com','Renewals'),
('Amy.Clarke@havenpower.com','Renewals'),
('Steven.Lawson@havenpower.com','Renewals'),
('David.Orchard@havenpower.com','Renewals'),
('Rhys.Waterman@havenpower.com','Renewals'),
('Limara.Ballantyne@havenpower.com','Direct Sales'),
('Jonathan.Huggins@havenpower.com','Direct Sales'),
('Karl.Brown@havenpower.com','Direct Sales'),
('Ashley.McSheen@havenpower.com','Direct Sales'),
('Craig.Parry@havenpower.com','Direct Sales'),
('Jerrell.Paton@havenpower.com','Direct Sales'),
('Leigh.Powell@havenpower.com','Direct Sales'),
('Halis.Toy@havenpower.com','Direct Sales'),
('Richard.Gooch@havenpower.com','Direct Admin'),
('Lisa.Gooderham@havenpower.com','Direct Admin'),
('Tiana.Artiss@havenpower.com','Direct Admin'),
('Trudi.McManus@havenpower.com','Direct Admin'),
('Lisa.Morris@havenpower.com','Direct Admin'),
('Aaron.Read@havenpower.com','Direct Admin'),
('Eddy.Semayobe@havenpower.com','Direct Admin'),
('James.Wallis@havenpower.com','Direct Admin'),
('Olivia.Hawkes@havenpower.com','Direct Admin'),
('Aliaha.Coe@havenpower.com','Contact'),
('Connor.Farrell@havenpower.com','Contact'),
('Michaela.Frost@havenpower.com','Contact'),
('Claire.Lock@havenpower.com','Contact'),
('Lucy.Martin@havenpower.com','Contact'),
('Sophie.Pearce@havenpower.com','Contact'),
('Oliver.Rayner@havenpower.com','Contact'),
('Suzanne.Dean@havenpower.com','COT/Trace'),
('Kimberley.Derrett@havenpower.com','COT/Trace'),
('Graham.Fincham@havenpower.com','COT/Trace'),
('Joanna.McLucas@havenpower.com','COT/Trace'),
('Nicola.Nelson@havenpower.com','COT/Trace'),
('Charlotte.Ripper@havenpower.com','COT/Trace'),
('Shanee.Theobald@havenpower.com','COT/Trace'),
('Rio.Tricker@havenpower.com','COT/Trace'),
('Aleksandra.Belousova@havenpower.com','Enterprise Billing'),
('Andrew.Cheesman@havenpower.com','Enterprise Billing'),
('Sonia.Easterbrook@havenpower.com','Enterprise Billing'),
('Robert.Fenn@havenpower.com','Enterprise Billing'),
('Antonia.Gleed@havenpower.com','Enterprise Billing'),
('Ambrosee.Harrison@havenpower.com','Enterprise Billing'),
('Toma.Stakutyte@havenpower.com','Enterprise Billing'),
('Nichole.Barnett@havenpower.com','Ledger'),
('Christopher.Dunning@havenpower.com','Ledger'),
('Ryan.Easy@havenpower.com','Ledger'),
('Sophie.Edrupt@havenpower.com','Ledger'),
('Ryan.Knapton@havenpower.com','Ledger'),
('Ben.Smith@havenpower.com','Ledger'),
('Carly.Eden@havenpower.com','Ledger'),
('Simone.Cotterill@havenpower.com','N/A'),
('Renee.Dunning@havenpower.com','N/A'),
('Susan.Gibson@havenpower.com','N/A'),
('Latisha.Laing@havenpower.com','N/A'),
('Kaspian.Oaken@havenpower.com','N/A'),
('Lucy.Parker@havenpower.com','N/A'),
('Rachel.Dockerill@havenpower.com','On/Off Boarding'),
('Hannah.Gillespie-Gardiner@havenpower.com','On/Off Boarding'),
('Niall.Johnson@havenpower.com','On/Off Boarding'),
('Joh.Mellows@havenpower.com','On/Off Boarding'),
('Megan.Rodgers@havenpower.com','On/Off Boarding'),
('Denzel.Stewart@havenpower.com','On/Off Boarding'),
('Matthew.Wyldering@havenpower.com','On/Off Boarding'),
('Tori.Ball@havenpower.com','Operations Team Leaders'),
('Monique.Dickerson@havenpower.com','Operations Team Leaders'),
('Clare.Garner@havenpower.com','Operations Team Leaders'),
('Amy.Tyler@havenpower.com','Operations Team Leaders'),
('Anna-Lisa.Barnes@havenpower.com','Support'),
('Giles.Petersen@havenpower.com','Support'),
('Suzanne.Abel@havenpower.com','Workflow'),
('Hollie.Burch@havenpower.com','Complaints'),
('Chloe.Cronin@havenpower.com','Complaints'),
('Jamie.Collett@havenpower.com','Complaints'),
('Megan.Driver@havenpower.com','Complaints'),
('Elizabeth.Flatt@havenpower.com','Complaints'),
('Kirk.Wright@havenpower.com','Complaints'),
('Charlotte.Barker@havenpower.com','Complaints'),
('Matthew.Price@havenpower.com','Complaint Escalations'),
('Elyse.Maloney@havenpower.com','Complaint Escalations'),
('Ashleigh.Rice@havenpower.com','Complaint Escalations'),
('David.Daniels@havenpower.com','CM Acc Rec/Insolvency'),
('Natalie.Southgate@havenpower.com','CM Acc Rec/Insolvency'),
('Gary.Tricker@havenpower.com','CM Acc Rec/Insolvency'),
('Rebecca.Brunning@havenpower.com','CM Acc Rec/Insolvency'),
('Zoe.Day@havenpower.com','CM Acc Rec/Insolvency'),
('Baksho.Kaur@havenpower.com','CM Collections'),
('Elizabeth.Brown@havenpower.com','CM Collections'),
('Michael.McVey@havenpower.com','CM Collections'),
('Suzanne.Murray@havenpower.com','CM Collections'),
('Amber.Houston@havenpower.com','CM Collections'),
('Christy.Feasey@havenpower.com','CM Collections'),
('Linda.Gildersleeves@havenpower.com','CM Collections'),
('Matthew.Smith@havenpower.com','CM Collections'),
('Martin.Dye@havenpower.com','CM Collections'),
('Stephanie.Harvey@havenpower.com','CM Collections'),
('Carl.Fairfull@havenpower.com','Escalated Debts'),
('Harriette.Hodgson@havenpower.com','Escalated Debts'),
('David.Cooper@havenpower.com','Escalated Debts'),
('Daniel.Hardy@havenpower.com','Escalated Debts'),
('Kim.Hinton@havenpower.com','Escalated Debts'),
('Victoria.Lazzari@havenpower.com','Escalated Debts'),
('Karla.Fumstone@havenpower.com','Escalated Debts'),
('Lucy.Ryman@havenpower.com','Escalated Debts'),
('Ryan.Gallant@havenpower.com','Escalated Debts'),
('Jessica.Baloga@havenpower.com','Escalated Debts'),
('Henna.Begum@havenpower.com','Smart Metering'),
('Simon.Grimwood@havenpower.com','Smart Metering'),
('Jorge.Hernandez@havenpower.com','Smart Metering'),
('Samuel.Martin@havenpower.com','Smart Metering'),
('Ellen.Noller@havenpower.com','Smart Metering'),
('Charlotte.Potter@havenpower.com','Smart Metering'),
('Jessica.Robinson@havenpower.com','Smart Metering'),
('Charlotte.Smith@havenpower.com','Smart Metering'),
('Steve.Lowry@havenpower.com','Smart Metering')
